AWSTemplateFormatVersion: 2010-09-09
Parameters:
  MyKeyName:
    Type: AWS::EC2::KeyPair::KeyName
    Description: Select Keypair from the list
  MyEnvironment:
    Type: String
    Default: Development
    AllowedValues: 
      - Development
      - Production
    ConstraintDescription: must be development or production 

Mappings:
  RegionMap:
    us-east-1:
      AMI: ami-0230bd60aa48260c6
    us-east-2:
      AMI: ami-06d4b7182ac3480fa
  EnvironmentMap:
    Development:
      InstanceType: t2.micro
    Production:
      InstanceType: t2.small

Conditions:
  CreateEIPProd: !Equals [!Ref MyEnvironment, Production]
  CreateSGforDev: !Equals [!Ref MyEnvironment, Development] 

Resources:
  MyEC2Instance:
    Type: "AWS::EC2::Instance"
    Properties:
      ImageId: !FindInMap
        - RegionMap
        - !Ref AWS::Region
        - AMI
      InstanceType: !FindInMap
        - EnvironmentMap
        - !Ref MyEnvironment
        - InstanceType
      KeyName: !Ref MyKeyName
      SecurityGroups: !If [CreateSGforDev, [!Ref MySecurityGroupforDev], !Ref 'AWS::NoValue']
  
  MySecurityGroupforDev:
    Type: AWS::EC2::SecurityGroup
    Condition: CreateSGforDev
    Properties:
      GroupDescription: My new security group
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: '22'
          ToPort: '22'
          CidrIp: 0.0.0.0/0

  ProdEIP:
    Type: AWS::EC2::EIP
    Condition: CreateEIPProd
    Properties:
      InstanceId: !Ref MyEC2Instance