AWSTemplateFormatVersion: 2010-09-09
Parameters:
  MyKeyPair1:
    Description: Select the key pair from drop down list
    Type: AWS::EC2::KeyPair::KeyName
  MyAvailabilityZone:
    Description: Select the availabily zone
    Type: String
    Default: us-east-1a
    AllowedValues:
      - us-east-1a
      - us-east-1b
      - us-east-1c
  MyInstanceType:
    Description: Select the instance type
    Type: AWS::SSM::Parameter::Value<String>
Resources:
  MyEC2Instance:
    Type: "AWS::EC2::Instance"
    Properties:
      ImageId: ami-0230bd60aa48260c6
      InstanceType: !Ref MyInstanceType
      KeyName: !Ref MyKeyPair1
      AvailabilityZone: !Ref MyAvailabilityZone
      SecurityGroups:
        - default
        - !Ref MySecurityGroup
  MySecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: My new security group
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: '22'
          ToPort: '22'
          CidrIp: 0.0.0.0/0
        - IpProtocol: tcp
          FromPort: '8080'
          ToPort: '8080'
          CidrIp: 0.0.0.0/0